plaintext = '''ANCIENT METHODS OF ENCRYPTION WERE BOTH FASCINATING AND EFFECTIVE.
LONG BEFORE MODERN COMPUTERS, GREAT MINDS LIKE AL-KINDI PAVED THE WAY.
KNOWLEDGE ABOUT THE PATTERNS IN LANGUAGES WAS HIS TOOL OF CHOICE.
INTRICACIES IN THE DISTRIBUTION OF LETTERS WERE HIS PLAYGROUND.
NUMEROUS ENCRYPTED TEXTS WERE DECRYPTED DUE TO HIS METHODS.
DELVE DEEP INTO HISTORY, AND YOU'LL FIND AL-KINDI'S MARK IN CRYPTANALYSIS.
IT'S A TESTAMENT TO HIS GENIUS THAT HIS METHODS STILL RESONATE TODAY.
DECODING MESSAGES REQUIRES BOTH INTUITION AND A KEEN UNDERSTANDING OF PATTERNS.
EVERY ENCRYPTED LETTER HAS A STORY, WAITING TO BE UNRAVELED.
CONCEPTS THAT AL-KINDI INTRODUCED HAVE LAID THE GROUNDWORK FOR FUTURE CRYPTANALYSTS.
OFTEN, LOOKING TO THE PAST CAN ILLUMINATE OUR CURRENT CHALLENGES.
DRAWING INSPIRATION FROM HIS WORK CAN CERTAINLY BENEFIT ANY ASPIRING CODEBREAKER.
EVEN THEN, TO FIND THE FLAG, LOOK NO FURTHER THAN THE FIRST LETTER OF EACH SENTENCE.
DON'T FORGET TO ENCAPSULATE IN CURLY BRACKETS AND PREPEND THE FLAG PREFIX.'''

alphabet = [chr(i) for i in range(ord('A'), ord('Z') + 1)]
alphabet_shuffle = ['Q', 'Y', 'L', 'W', 'J', 'A', 'X', 'N', 'O', 'C', 'I', 'U', 'F',
                    'K', 'Z', 'D', 'B', 'E', 'H', 'T', 'R', 'S', 'V', 'G', 'M', 'P']
ciphermap = dict(zip(alphabet, alphabet_shuffle))

ciphertext = ''
for c in map(lambda x: ciphermap[x] if x in alphabet_shuffle else x, plaintext):
    ciphertext += c
print(ciphertext)

file = open('ciphertext.txt', 'w')
file.write(ciphertext)
file.close()
